---
openapi: 3.0.1
info:
  title: Документация API V1
  description: API тестового сервиса обучающих курсов
  version: v1
paths:
  "/api/v1/authors/{author_id}/courses":
    parameters:
    - name: author_id
      in: path
      required: true
      description: ID автора
      schema:
        type: integer
    get:
      summary: Получить список курсов автора
      tags:
      - Курсы автора
      responses:
        '200':
          description: Успешный запрос
        '404':
          description: Автор не найден
    post:
      summary: Добавить автору новый курс
      tags:
      - Курсы автора
      parameters: []
      responses:
        '201':
          description: Курс успешно создан
        '422':
          description: Некорректный запрос
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - title
              - description
              properties:
                title:
                  type: string
                description:
                  type: string
                content:
                  type: string
  "/api/v1/authors/{author_id}/courses/{id}":
    parameters:
    - name: author_id
      in: path
      required: true
      description: ID автора
      schema:
        type: integer
    - name: id
      in: path
      required: true
      description: ID курса
      schema:
        type: integer
    get:
      summary: Показать курс автора
      tags:
      - Курсы автора
      responses:
        '200':
          description: Успешный запрос
        '404':
          description: Автор или курс не найден
    put:
      summary: Обновить данные курса автора
      tags:
      - Курсы автора
      parameters: []
      responses:
        '200':
          description: Успешно обновлено
        '422':
          description: Недопустимый запрос
        '404':
          description: Курс не найден
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                content:
                  type: string
    delete:
      summary: Удалить курс у автора
      tags:
      - Курсы автора
      responses:
        '204':
          description: Успешно удалено
        '404':
          description: Курс не найден
  "/api/v1/authors":
    get:
      summary: Список авторов
      tags:
      - Авторы
      parameters:
      - name: page
        in: query
        required: false
        description: Номер страницы
        schema:
          type: integer
      responses:
        '200':
          description: Успешный запрос
    post:
      summary: Создать нового автора
      tags:
      - Авторы
      parameters: []
      responses:
        '201':
          description: Успешный запрос
        '422':
          description: Отсутствуют необходимые поля
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
              required:
              - first_name
              - last_name
              - email
        required: true
  "/api/v1/authors/{id}":
    parameters:
    - name: id
      in: path
      description: ID автора
      required: true
      schema:
        type: string
    get:
      summary: Получить данные автора
      tags:
      - Авторы
      description: Возвращает данные автора вместе с его курсами
      responses:
        '200':
          description: Успешно
    put:
      summary: Изменить данные автора
      tags:
      - Авторы
      parameters: []
      responses:
        '200':
          description: Успешный запрос
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
              required:
              - first_name
              - last_name
              - email
    delete:
      summary: Удалить автора
      tags:
      - Авторы
      description: Прежде чем удалить указанного автора, находит случайного автора
        и назначает ему курсы удаляемого автора.
      responses:
        '200':
          description: Автор успешно удален. Данные нового автора возвращаются в теле
            ответа.
        '500':
          description: Не удалось найти замену автора.
  "/api/v1/courses/{course_id}/skills":
    parameters:
    - name: course_id
      in: path
      description: ID курса
      required: true
      schema:
        type: string
    get:
      summary: Получить список компетенций курса
      tags:
      - Компетенции курса
      responses:
        '200':
          description: Успешный запрос
    post:
      summary: Создание компетенции для курса
      tags:
      - Компетенции курса
      parameters: []
      responses:
        '201':
          description: Компетенция создана
        '422':
          description: Недопустимый запрос
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
              - name
  "/api/v1/courses/{course_id}/skills/{skill_id}":
    parameters:
    - name: course_id
      in: path
      description: ID курса
      required: true
      schema:
        type: string
    - name: skill_id
      in: path
      description: ID компетенции
      required: true
      schema:
        type: string
    delete:
      summary: Удаляет компетенцию у курса
      tags:
      - Компетенции курса
      responses:
        '204':
          description: Компетенция курса удалена
        '404':
          description: Компетенция не найдена
servers:
- url: http://localhost:3000
  variables: {}
