---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/authors/{author_id}/courses":
    parameters:
    - name: author_id
      in: path
      required: true
      description: Author ID
      schema:
        type: integer
    post:
      summary: Create a course
      tags:
      - Courses
      parameters: []
      responses:
        '201':
          description: course created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - title
              - description
              properties:
                title:
                  type: string
                description:
                  type: string
  "/api/v1/authors/{author_id}/courses/{course_id}":
    parameters:
    - name: author_id
      in: path
      description: author id
      required: true
      schema:
        type: string
    - name: course_id
      in: path
      description: course id
      required: true
      schema:
        type: string
    get:
      summary: Получить расширенные данные курса автора
      responses:
        '200':
          description: Успешно
  "/api/v1/authors/{author_id}/courses/{id}":
    parameters:
    - name: author_id
      in: path
      required: true
      description: Author ID
      schema:
        type: integer
    - name: id
      in: path
      required: true
      description: Course ID
      schema:
        type: integer
    get:
      summary: Show a course
      tags:
      - Courses
      responses:
        '200':
          description: successful
        '404':
          description: not found
    put:
      summary: Update a course
      tags:
      - Courses
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: invalid request
        '404':
          description: not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                content:
                  type: string
    delete:
      summary: Delete a course
      tags:
      - Courses
      responses:
        '204':
          description: successful
        '404':
          description: not found
  "/api/v1/authors":
    get:
      summary: Список авторов
      parameters:
      - name: page
        in: query
        required: false
        description: Номер страницы
        schema:
          type: integer
      responses:
        '200':
          description: successful
    post:
      summary: Создать нового автора
      parameters: []
      responses:
        '201':
          description: successful
        '422':
          description: Отсутствуют необходимые поля
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
              required:
              - first_name
              - last_name
              - email
        required: true
  "/api/v1/authors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Получить данные автора
      description: Возвращает данные автора вместе с его курсами
      responses:
        '200':
          description: Успешно
    put:
      summary: Изменить данные автора
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
              required:
              - first_name
              - last_name
              - email
    delete:
      summary: Удалить автора
      description: Прежде чем удалить указанного автора, находит случайного автора
        и назначает ему курсы удаляемого автора.
      responses:
        '200':
          description: Автор успешно удален. Данные нового автора возвращаются в теле
            ответа.
        '500':
          description: Не удалось найти замену автора.
  "/api/v1/courses/{course_id}/skills":
    parameters:
    - name: course_id
      in: path
      description: ID of the course
      required: true
      schema:
        type: string
    post:
      summary: Creates a skill for a course
      tags:
      - Skills
      parameters: []
      responses:
        '201':
          description: skill created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
              - name
  "/api/v1/courses/{course_id}/skills/{skill_id}":
    parameters:
    - name: course_id
      in: path
      description: ID of the course
      required: true
      schema:
        type: string
    - name: skill_id
      in: path
      description: ID of the skill
      required: true
      schema:
        type: string
    delete:
      summary: Deltes a skill for a course
      tags:
      - Skills
      responses:
        '204':
          description: skill deleted
        '404':
          description: skill not found
servers:
- url: http://localhost:3000
  variables: {}
