default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: courses_development

test:
  <<: *default
  database: courses_test
